### ISSUE TITLE
Similarly named plugin causes update problems

### ISSUE THREAD

**Issue by hashimwarren** [TylerBarnes/using-gatsby-source-wordpress-experimental#1]
<img width="524" alt="wp-gatsby-naming" src="https://user-images.githubusercontent.com/6027587/73878890-430fb180-4810-11ea-907d-e5d685432468.png">

After installing the WP-gatsby plugin, WordPress is asking me to update to plugin with the same name on the WP.org repo

This is the plugin with the same name - https://wordpress.org/plugins/wp-gatsby/

**Comment by TylerBarnes** [comment]
@hashimwarren thanks for bringing this up!
@jasonbahl spoke with the owner of the original WP Gatsby (I believe @lightstrike), and he is happy to transfer ownership to us. For now I think we will have to ignore that message until we do our first release of WPGatsby.

**Comment by TylerBarnes** [comment]
I'll add a note to the readme for now

**Comment by TylerBarnes** [comment]
I bumped the version number higher than the one on the WP plugin repo, so this message doesn't show up anymore.

**Comment by jasonbahl** [comment]
I wonder if we publish a super bare bones version to clear out what exists today in that plugin. 

Something with a README on what we're up to, etc. 🤔
