### ISSUE TITLE
connected object in wp menu is not connected in any post

### ISSUE THREAD

**Issue by muhzulzidan** [TylerBarnes/using-gatsby-source-wordpress-experimental#10]
```
connectedObject {
              ... on WpContentNode {
                uri
              }
            }
```
and it is not exist

```WpPost
WpPage
WpCategory
WpTag
WpMenuItem
```

only above exists

**Comment by TylerBarnes** [comment]
Hi @muhzulzidan thanks for the bug report! Can you elaborate a bit more? I'm not entirely sure what you mean. Thanks!

**Comment by muhzulzidan** [comment]
it is from in the menu components. 

in graphql,  ... on WpContentNode does not exists,

when i check it on graphql, it does not exists... these exist instead,  
```
WpPage
WpCategory
WpTag
WpMenuItem
```


if i want to have a catagories that connected to the post, i must use the allcatogories instead... and it will be another form of code

**Comment by TylerBarnes** [comment]
Huh, ContentNode should exist there. Are you able to share a minimal reproduction repo so I can have a look?
Thanks

**Comment by muhzulzidan** [comment]
https://github.com/muhzulzidan/wp-experimental/tree/afa

**Comment by TylerBarnes** [comment]
Can you share your GraphQL api? I can't reproduce locally

**Comment by muhzulzidan** [comment]
i will email you sir..

**Comment by TylerBarnes** [comment]
Hi @muhzulzidan , I had a look and the reason is that you're asking for WpContentNode types on your connectedObject field but you don't have any. You have WpCategory types. WpContentNode only lists content types which is a synonym in WPGraphQL for post types.

Try this:

```
{
  allWpMenu {
    nodes {
      menuItems {
        nodes {
          connectedObject {
            __typename
            ... on WpCategory {
              id
            }
            ... on WpContentNode {
              id
            }
          }
        }
      }
    }
  }
}
```

If you make a query and add `__typename` when you're using inline fragments it will tell you which type each node is then you know which inline fragments you'll need to add.

**Comment by TylerBarnes** [comment]
```json
{
  "data": {
    "allWpMenu": {
      "nodes": [
        {
          "menuItems": {
            "nodes": [
              {
                "connectedObject": {
                  "__typename": "WpCategory",
                  "id": "Y2F0ZWdvcnk6MQ=="
                }
              },
              {
                "connectedObject": {
                  "__typename": "WpCategory",
                  "id": "Y2F0ZWdvcnk6MTk="
                }
              },
              {
                "connectedObject": {
                  "__typename": "WpCategory",
                  "id": "Y2F0ZWdvcnk6MTY="
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```
