### ISSUE TITLE
Unable to connect to WPGraphQL

### ISSUE THREAD

**Issue by mpaccione** [TylerBarnes/using-gatsby-source-wordpress-experimental#12]
1. Downloaded Repo
2. Installed Both Plugins into Wordpress Site 
3. Changed URL in gatsby-config.js

4. ERROR: Unable to connect to WPGraphQL

http://agencydb.giddyuppupsf.com/graphql

This is running the stock 2020 Theme is Wordpress and has no custom plugins other than the ones provided in the docs.

**Comment by mpaccione** [comment]
Also Im in Ubuntu with Node v12.16.2 and using the existing repo I get this error just stock, ran it with sudo...

```
⠙ Building development bundle
/usr/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

TypeError: Cannot destructure property 'activationValue' of 'undefined' as it is undefined.
    at /home/mpaccione/Projects/wordpress-v4/node_modules/gatsby-plugin-notifications/gatsby-node.js:47:36
    at /home/mpaccione/Projects/wordpress-v4/node_modules/node-notifier/lib/utils.js:65:5
    at ChildProcess.exithandler (child_process.js:294:7)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:310:20)
    at Pipe.<anonymous> (net.js:672:12)
```

**Comment by TylerBarnes** [comment]
Hi @mpaccione , it looks like that problem is with gatsby-plugin-notifications. If you remove it you should be good
