### ISSUE TITLE
Unique Key error for Menu items

### ISSUE THREAD

**Issue by imranhsayed** [TylerBarnes/using-gatsby-source-wordpress-experimental#14]
The Link needs to have the key instead of button in menu component

https://github.com/TylerBarnes/using-gatsby-source-wordpress-experimental/blob/bce80b6063ecb60daeebb4c588242f025eadfa86/src/components/menu.js#L35

![image](https://user-images.githubusercontent.com/11497423/80804431-c43dd100-8bd2-11ea-969b-517b2768cc6c.png)

This [PR](https://github.com/TylerBarnes/using-gatsby-source-wordpress-experimental/pull/13) fixes that issue

**Comment by TylerBarnes** [comment]
Closing this as the PR has been merged. Thanks @imranhsayed !
