### ISSUE TITLE
Preview with draft and private post

### ISSUE THREAD

**Issue by hazuremon** [TylerBarnes/using-gatsby-source-wordpress-experimental#17]
I have managed to get preview to work for published post, but not for draft and private post and getting 404 page as a result. Does preview work with these post status or only for published post?

Running:
- WP Gatsby 0.4.8
- WP GraphQL 0.10.2
- WP 5.4.2
- gatsby-source-wordpress-experimental 1.0.2
- Tried preview on Gatsby Cloud and locally through ngrok with same results

**Comment by adriandmitroca** [comment]
how have you managed to work with previews? gatsby cloud, or something normal lol?

**Comment by hazuremon** [comment]
I am using Gatsby Cloud, then further testing it locally through ngrok

**Comment by hazuremon** [comment]
It's probably better suit in the gatsby-source-wordpresss-experimental repo, as I tried another starter theme and having same results, will close this instead.
