### ISSUE TITLE
The result of this StaticQuery could not be fetched at menu.js

### ISSUE THREAD

**Issue by bebjakub** [TylerBarnes/using-gatsby-source-wordpress-experimental#18]
Hello, 
after install latest starter, and configuring source endpoint & run `gatsby build` I got `The result of this StaticQuery could not be fetched.` Btw. when I run `gatsby develop` there is no error.

![image](https://user-images.githubusercontent.com/10927960/88373274-dbd2c300-cd97-11ea-8d54-a8b720084d2c.png)

btw. when I query it in WP GraphiQL via `menu` query menu exists, but there is no result with `wpMenu` or `allWpMenu` in Gatsby GraphiQL.

Steps to reproduce:
1. Install starter
2. configure source endpoint
3. gatsby build

Mac OS, Chrome (latest)
WP GraphQL 0.10.3
WP Gatsby 0.4.13
WP GraphiQL 1.0.1

Thanks

**Comment by TylerBarnes** [comment]
Hi @bebjakub , this sounds like a Gatsby core issue. Can you run `gatsby info` and copy/paste the output here?

**Comment by bebjakub** [comment]
```
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    npm: 6.14.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.89
    Firefox: 72.0.2
    Safari: 13.1.1
  npmPackages:
    gatsby: 2.22.5 => 2.22.5
    gatsby-image: ^2.4.13 => 2.4.13
    gatsby-plugin-chakra-ui: ^0.1.4 => 0.1.4
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.6.19 => 2.6.21
    gatsby-source-filesystem: ^2.3.7 => 2.3.22
    gatsby-source-wordpress-experimental: 1.0.7 => 1.0.7
    gatsby-transformer-sharp: 2.5.11 => 2.5.11
    gatsby-wordpress-experimental-inline-images: ^0.0.3 => 0.0.3
  npmGlobalPackages:
    gatsby-cli: 2.12.65
```

**Comment by TylerBarnes** [comment]
Looks like others are also having this issue https://github.com/gatsbyjs/gatsby/issues/25987 so I believe this is a core bug. Lets track this in that issue instead

**Comment by TylerBarnes** [comment]
Actually lets track it in this issue https://github.com/gatsbyjs/gatsby/issues/25985
