### ISSUE TITLE
error when get raw price

### ISSUE THREAD

**Issue by nguyenhuutinh** [TylerBarnes/using-gatsby-source-wordpress-experimental#25]
hi, how to get rawprice on woo?
I tried
.

.. on WpSimpleProduct {
          price(format: RAW)
 }
but got error when compile.
Unknown argument "format" on field "price" of type "WpSimpleProduct".

thanks

**Comment by TylerBarnes** [comment]
Hi @nguyenhuutinh , Woo may work with the new source plugin but isn't currently officially supported. We will have a push in the near future where we ensure Woo works with Gatsby. Thanks!
