### ISSUE TITLE
WP Gatsby Plugin Fatal Error / Ensure earliest supported PHP version in WPGQL is supported in WPGatsby

### ISSUE THREAD

**Issue by pjsachdev** [TylerBarnes/using-gatsby-source-wordpress-experimental#3]
Great work so far on the new gatsby source wordpress plugin. 

I've encountered an issue with the WP Gatsby plugin. When I install it on a WordPress site, I get the following fatal error.

`Parse error: syntax error, unexpected ')' in /app/public/wp-content/plugins/wp-gatsby/src/ActionMonitor/ActionMonitor.php on line 62 `

Removing the trailing comma on line 61 of ActionMonitor.php seems to fix the issue.

**Comment by TylerBarnes** [comment]
Yep, looks like I'm writing code that only works in PHP 7.x
I'll have to downgrade my local PHP version and make sure it's compatible with whichever version WPGQL is compatible with.

Thanks for opening this issue!

**Comment by TylerBarnes** [comment]
This was fixed a couple months ago :p closing now :)
